### ISSUE TITLE
Blank line using yapf for python formatting

### ISSUE THREAD

**Issue by RMTT** [mattn/efm-langserver#188] opened 2021-11-21 05:12 UTC
Using efm with nvim built-in lsp:
```lua
require'lspconfig'.efm.setup {
    init_options = {documentFormatting = true},
    settings = {
        rootMarkers = {'.git'},
        languages = {
            lua = {{formatCommand = 'lua-format -i', formatStdin = true}},
            python = {{formatCommand = 'yapf', formatStdin = true}}
        }
    }
}
```
When i format such a main.py:
```python
1. print(1,                           2)
```
The result is abnormal:
```python
1. 
2. print(1, 2)
```
But it's ok when using yapf from terminal:
```shell
> yapf main.py
print(1, 2)
```

**Comment by gjeusel** [comment] 2021-11-23 15:37
Duplicate of https://github.com/mattn/efm-langserver/issues/181

**Closed** 2021-11-28 11:48 UTC
